defmodule SymphonyElixir.Workpad do
  @moduledoc """
  Local per-run workpad helpers.

  The GitHub issue remains the durable control surface. This file is a local
  run ledger that gives Codex an immediate, inspectable place to anchor plan
  and evidence before product code changes exist.
  """

  require Logger
  alias SymphonyElixir.Linear.Issue

  @directory ".symphony"
  @filename "workpad.md"
  @exclude_entry ".symphony/"

  @spec path(Path.t()) :: Path.t()
  def path(workspace) when is_binary(workspace) do
    workspace
    |> Path.join(@directory)
    |> Path.join(@filename)
  end

  @spec bootstrap(Path.t(), Issue.t() | map()) :: :ok | {:error, term()}
  def bootstrap(workspace, issue), do: bootstrap(workspace, issue, nil)

  @spec bootstrap(Path.t(), Issue.t() | map(), term()) :: :ok | {:error, term()}
  def bootstrap(_workspace, _issue, worker_host) when is_binary(worker_host), do: :ok

  def bootstrap(workspace, issue, _worker_host) when is_binary(workspace) do
    with :ok <- ensure_local_workspace(workspace),
         :ok <- ensure_git_exclude(workspace),
         :ok <- write_workpad(workspace, issue) do
      :ok
    else
      {:error, reason} = error ->
        Logger.warning("Failed to bootstrap Symphony workpad workspace=#{workspace} reason=#{inspect(reason)}")
        error
    end
  rescue
    error in [File.Error, ArgumentError] ->
      reason = Exception.message(error)
      Logger.warning("Failed to bootstrap Symphony workpad workspace=#{workspace} reason=#{reason}")
      {:error, reason}
  end

  @spec fingerprint(Path.t()) :: {:ok, integer()} | :missing
  def fingerprint(workspace) when is_binary(workspace) do
    workpad_path = path(workspace)

    if File.regular?(workpad_path), do: fingerprint_file(workpad_path), else: :missing
  rescue
    _ -> :missing
  end

  defp fingerprint_file(workpad_path) do
    case File.read(workpad_path) do
      {:ok, content} -> fingerprint_content(content)
      {:error, _reason} -> :missing
    end
  end

  defp fingerprint_content(content) when is_binary(content) do
    case String.trim(content) do
      "" -> :missing
      trimmed_content -> {:ok, :erlang.phash2(trimmed_content)}
    end
  end

  defp ensure_local_workspace(workspace) do
    if File.dir?(workspace) do
      File.mkdir_p!(Path.join(workspace, @directory))
      :ok
    else
      {:error, :missing_workspace}
    end
  end

  defp ensure_git_exclude(workspace) do
    git_dir = Path.join(workspace, ".git")

    if File.dir?(git_dir) do
      exclude_path = Path.join([git_dir, "info", "exclude"])
      File.mkdir_p!(Path.dirname(exclude_path))
      existing = if File.regular?(exclude_path), do: File.read!(exclude_path), else: ""

      if exclude_present?(existing) do
        :ok
      else
        File.write!(exclude_path, append_exclude(existing))
        :ok
      end
    else
      :ok
    end
  end

  defp exclude_present?(content) do
    content
    |> String.split("\n")
    |> Enum.map(&String.trim/1)
    |> Enum.member?(@exclude_entry)
  end

  defp append_exclude(""), do: "# Symphony local run ledger\n#{@exclude_entry}\n"

  defp append_exclude(content) do
    separator = if String.ends_with?(content, "\n"), do: "", else: "\n"
    content <> separator <> "# Symphony local run ledger\n#{@exclude_entry}\n"
  end

  defp write_workpad(workspace, issue) do
    workpad_path = path(workspace)
    stamp = DateTime.utc_now() |> DateTime.truncate(:second) |> DateTime.to_iso8601()

    content =
      case File.read(workpad_path) do
        {:ok, existing} when existing != "" ->
          existing <> "\n\n" <> run_stamp(stamp, workspace)

        _ ->
          initial_content(issue, workspace, stamp)
      end

    File.write!(workpad_path, content)
    :ok
  end

  defp initial_content(issue, workspace, stamp) do
    """
    # Symphony Workpad

    Generated by Symphony before Codex starts. Keep this local run ledger out of commits; GitHub issues and PRs remain the durable handoff surface.

    ## Issue

    - Identifier: #{issue_value(issue, :identifier) || issue_value(issue, :id) || "unknown"}
    - Number: #{issue_value(issue, :number) || "unknown"}
    - Title: #{issue_value(issue, :title) || "untitled"}
    - State: #{issue_value(issue, :state) || "unknown"}
    - Repository: #{repository(issue)}
    - URL: #{issue_value(issue, :url) || "unknown"}
    - Labels: #{labels(issue)}

    ## Workspace

    - Path: #{workspace}
    - Branch: #{git_output(workspace, ["branch", "--show-current"])}
    - HEAD: #{git_output(workspace, ["rev-parse", "--short", "HEAD"])}
    - Started: #{stamp}

    ## Operating Notes

    - Use this file as local scratch evidence while you work.
    - Move quickly from orientation to an issue-relevant code, test, fixture, or validation artifact.
    - Keep the GitHub `## Codex Workpad` comment useful for operator-visible milestones, but do not let comment bookkeeping delay repo work.
    - Do not commit `.symphony/`; it is Symphony runtime state.

    ## Plan

    - [ ] Reconcile the issue and branch state.
    - [ ] Capture the smallest useful reproduction or characterization signal.
    - [ ] Implement the requested change with focused validation.
    - [ ] Update the durable GitHub workpad at meaningful checkpoints.
    - [ ] Open or update the PR with evidence.

    ## Evidence

    #{run_stamp(stamp, workspace)}
    """
  end

  defp run_stamp(stamp, workspace) do
    """
    - #{stamp}: Symphony started or resumed this run in `#{workspace}` on branch `#{git_output(workspace, ["branch", "--show-current"])}` at `#{git_output(workspace, ["rev-parse", "--short", "HEAD"])}`.
    """
    |> String.trim()
  end

  defp issue_value(%Issue{} = issue, key), do: Map.get(issue, key)
  defp issue_value(issue, key) when is_map(issue), do: Map.get(issue, key) || Map.get(issue, to_string(key))
  defp issue_value(_issue, _key), do: nil

  defp repository(issue) do
    case {issue_value(issue, :repo_owner), issue_value(issue, :repo_name)} do
      {owner, name} when is_binary(owner) and is_binary(name) -> "#{owner}/#{name}"
      _ -> "unknown"
    end
  end

  defp labels(issue) do
    case issue_value(issue, :labels) do
      labels when is_list(labels) -> Enum.join(labels, ", ")
      _ -> ""
    end
  end

  defp git_output(workspace, args) do
    case System.cmd("git", args, cd: workspace, stderr_to_stdout: true) do
      {output, 0} ->
        output
        |> String.trim()
        |> blank_as_unknown()

      _ ->
        "unknown"
    end
  rescue
    _ -> "unknown"
  end

  defp blank_as_unknown(""), do: "unknown"
  defp blank_as_unknown(value), do: value
end
